#!/bin/bash

PATH=${GEMSTONE}/bin:${PATH}

startnetldi -g -a gsadmin -l ${CDS_GEMSTONE_NETLDI_LOG} -D ${CDS_GEMSTONE_NETLDI_CLIENT_LOG_DIR}
startstone  gs64stone


while true; do
    gslist -v
    echo 'Sleeping...'
    sleep 60
done

